### ISSUE TITLE
What's the maintenance status?

### ISSUE THREAD

**Issue by Brideau** [locationtech/proj4j#1]
Hi there, I came across [this proposal](https://www.locationtech.org/proposals/proj4j) and was wondering if there is still a plan to maintain this library? The repo linked in the proposal is [this one](https://github.com/dwins/proj4j) by @dwins and it looks like the original is over in the [Proj4j organization](https://github.com/Proj4J/proj4j/), but it's getting pretty stale. It seemed to receive a series of updates a couple years ago, but there hasn't been a new release.

Would be great to see a group pick this up again!

**Comment by dr-jts** [comment]
Yes, it would be great to invigorate this project.  

I note that the LT homepage needs some curating as well (some spam in comments).

**Comment by willcohen** [comment]
This project does meet a need as a reprojection tool which is both lightweight and Apache-licensed, especially re the JTS 1.15 licensing change. Is it worth putting out a 0.1.1 release of this version which incorporates the geotrellis bug fixes and updates, pending a larger discussion of changes to the code base? Alternatively, would a recommendation be for other projects to just incorporate geotrellis-proj4 in the meantime?

**Comment by echeipesh** [comment]
This proj4j is now alive here and is being maintained. It has recently picked up a couple more committers and there are conversations about future feature development that should surface both on dev list and issue list here. I think this issue is resolved.
