### ISSUE TITLE
Will there be support for +geoidgrids ? its commonly used for height transformation

### ISSUE THREAD

**Issue by lemontmoon** [locationtech/proj4j#102]
Hi.

Our transformation uses Slovakia_ETRS89h_to_Baltic1957.gtx file that should be used as geoidgrid

Will there be support for +geoidgrids soon ? With some python code we can get correct transformations, but maybe because of we cant use .gtx file for transformation using proj4 yet, we are getting height always around 0.17 meters.

our example : 

```java
CoordinateReferenceSystem ETRS89 = 
  CRS.createFromParameters(
    "lonlat", 
    "+proj=longlat +ellps=bessel +towgs84=589,76,480,0,0,0,0 +no_defs +nadgrids=Slovakia_JTSK03_to_JTSK.gsb"
  );

CoordinateReferenceSystem SJSTK = 
  CRS.createFromParameters(
    "5514", 
    "+proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=485.021,169.465,483.839,7.786342,4.397554,4.102655,0 +units=m +no_defs +geoidgrids=Slovakia_ETRS89h_to_Baltic1957.gtx"
  ); 
```

I have imported files correctly, so we can get lon lat correctly, but height is incorrect.

Thanks.

**Comment by pomadchin** [comment]
Hello, that's been not on the radar, and any help with implementing support for this feature is highly appreciated!

**Comment by pomadchin** [comment]
Duplicate! https://github.com/locationtech/proj4j/issues/20
