### ISSUE TITLE
Unknown projection: longlat

### ISSUE THREAD

**Issue by Tom3652** [locationtech/proj4j#111]
Thanks for the package !

When i try to transform EPSG:2154 i am getting this error : `Unkown projection: longlat`

From this method :

```java
 private Projection parseProjection(Map params, Ellipsoid ellipsoid) {
        Projection projection = null;

        String s;
        s = (String) params.get(Proj4Keyword.proj);
        if (s != null) {
            projection = registry.getProjection(s);
            if (projection == null)
                throw new InvalidValueException("Unknown projection: " + s); // Here
        }
		else {
			throw new InvalidValueException("Keyword '" + Proj4Keyword.proj + "' is a required parameter");
        }
        projection.setEllipsoid(ellipsoid);
      ... 
 }
```

I am using this method to call the transform : 

```java
 public ProjCoordinate transform(double lon, double lat) {
        try {
            CRSFactory factory = new CRSFactory();
            CoordinateReferenceSystem srcCrs = factory.createFromName("EPSG:4326");
            CoordinateReferenceSystem dstCrs = factory.createFromName("EPSG:2154");
            BasicCoordinateTransform transform = new BasicCoordinateTransform(srcCrs, dstCrs);
            ProjCoordinate srcCoord = new ProjCoordinate(lon, lat);
            ProjCoordinate dstCoord = new ProjCoordinate();
            transform.transform(srcCoord, dstCoord);
            Log.d(TAG, "Dst Coordinates : " + dstCoord.toShortString());
            return dstCoord;
        } catch (Exception e) {
            onError("Error transforming lat " + lat + " - lng " + lon + " : " + e.getMessage());
        }
        return null;
    }
```

The entire error message i have is : `Error transforming lat 43.094308831666566 - Ing 5.825118781666667 Unknown projection: longlat`
So i have checked that my lat - lng were correct and it actually works fine sometimes, sometimes i have the error.

Can i know more why i have this error and how can i fix it please ?

**Comment by pomadchin** [comment]
hi @Tom3652, how is proj4j added into the project? also what version is the project dependent on?

**Comment by Tom3652** [comment]
Hello @pomadchin ! 
Thanks for your reply, it is added in the `app/build.gradle` file this way : 

```
implementation 'org.locationtech.proj4j:proj4j:1.3.0'
implementation 'org.locationtech.proj4j:proj4j-epsg:1.3.0'
```

I have also tried an older version that doesn't use the separated package `proj4j-epsg` : `implementation 'org.locationtech.proj4j:proj4j:1.1.5'` but i am getting the same error.
I have an app released on the store with version `implementation 'org.locationtech.proj4j:proj4j:1.1.3'` working fine. 

Don't hesitate if you need more information !

**Comment by pomadchin** [comment]
The only idea I can come up is that no projection files in the classapatch are causing this error

**Comment by pomadchin** [comment]
If it works in the studio but not in a shape of a package => that's definitely smth related to packaging. 

// I haven't dealt with Androd for quite some time

**Comment by Tom3652** [comment]
Thanks for your reply, at least i know this something related to this, i will try to figure it out and post a solution here when i found one.

**Comment by pomadchin** [comment]
Great! Feel free to drop here anything; I'll try to help u as much as I can!

**Comment by Tom3652** [comment]
Thank you very much, really apreciated !
I am planning to call few methods from the `proj4j-epsg` package with fake params (and display the output) just to make sure the package is imported in the released bundled app 🙏🏻

**Comment by pomadchin** [comment]
@Tom3652 Btw, `proj4j-epsg` is just a bunch of files from its [resources](https://github.com/locationtech/proj4j/tree/master/epsg/src/main/resources) folder

**Comment by Tom3652** [comment]
Well i see that there are plenty of `longlat` inside the `proj` field : 

<img width="484" alt="Capture d’écran 2024-04-18 à 16 16 06" src="https://github.com/locationtech/proj4j/assets/32631467/c3008f13-ec40-437b-9153-9727a7693e18">

Is there any chance that when i call `CoordinateReferenceSystem dstCrs = factory.createFromName("EPSG:2154");` it maps towards a bad `Projection` ? 

Because if i have this error, in my opinion it means it actually reads the file but parse the "wrong" `+proj` field no ? 

-> I am telling this because i just got the issue in `debug` mode... So it's not related to `release` only but doesn't happen every single time in `debug`

**Comment by pomadchin** [comment]
Looking closer now.

`Unknown projection` happens only [here](https://github.com/locationtech/proj4j/blob/b327b33eddf9be8b7540c53f26ba1c0f1f909c05/core/src/main/java/org/locationtech/proj4j/parser/Proj4Parser.java#L74) meaning it has not latlon projection in the registry.

Registry is declared [over there](https://github.com/locationtech/proj4j/blob/b327b33eddf9be8b7540c53f26ba1c0f1f909c05/core/src/main/java/org/locationtech/proj4j/CRSFactory.java#L40)

and it is purely [in mem](https://github.com/locationtech/proj4j/blob/b327b33eddf9be8b7540c53f26ba1c0f1f909c05/core/src/main/java/org/locationtech/proj4j/Registry.java#L213-L216)

Wondering what happens to the project init on your app side. Definitely need to be a reproducible example to assist further :/

**Comment by Tom3652** [comment]
Thank you very much, i had not followed the in mem insight you gave me but indeed there is defintely no "reason" it happens

Will run more tests and see if i can debug it further, until forking the project and add some debug logs if i have to 😅

**Comment by pomadchin** [comment]
Oh, in mem is that this registry is just a HashMap filled in in the object constructor. 

Wondering how the debug mode may affect it 🤔

**Comment by Tom3652** [comment]
Alright i am getting closer, i have logged this : 

```
public ProjCoordinate transform(double lon, double lat) {
        CoordinateReferenceSystem srcCrs = null;
        CoordinateReferenceSystem dstCrs = null;
        try {
            CRSFactory factory = new CRSFactory();
            List<Projection> projections = factory.getRegistry().getProjections();
            if (projections.isEmpty()) {
                onError("No projections found in registry !");
            }
            for (int i = 0; i < projections.size(); i++) {
                Projection projection = projections.get(i);
                onError("Getting projection code : " + projection.getEPSGCode() + " with name : " + projection.getName());
            }
            srcCrs = factory.createFromName("EPSG:4326");
            dstCrs = factory.createFromName("EPSG:2154");
        } catch (Exception e) {
            Log.d(TAG, "Error transforming lat - lng : " + e);
            // onError("Error creating coordinates lat " + lat + " - lng " + lon + " : " + e.getMessage());
        }
}
```

And i am getting `No projections found in registry !`, so i need to figure out why there are no projections in the registry 😂 (the `registry` is not `null` though) !

**Comment by Tom3652** [comment]
It really makes me wonder if the commented lines at the begining of this method are actually very useful in release mode : 

```
public Projection getProjection(String name) {
        // if ( projRegistry == null )
        // initialize();
        Class cls = (Class) projRegistry.get(name);
        if (cls != null) {
            try {
                Projection projection = (Projection) cls.newInstance();
                if (projection != null)
                    projection.setName(name);
                return projection;
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (InstantiationException e) {
                System.err.println("Cannot instantiate projection " + name + " [" + cls.getName() + "]");
                e.printStackTrace();
            }
        }
        return null;
    }
```
Because it seems there is an issue with `projRegistry` in release mode :/ 

```
// if ( projRegistry == null )
        // initialize();
```

**Comment by Tom3652** [comment]
Hello @pomadchin , do you think it might be a bug now ? 
Knowing that this is the `registry` that is empty, i am not sure i can do much, the packaging seems fine, this is more looking like some race condition 

Do you think this might be happening because of the `register` method ? the weird part is that it's like the `register` method is never called in release mode, the "only" guess point i can make at this moment is that `projRegistry != null` but `projRegistry` is empty : 

![Capture d’écran 2024-04-22 à 17 23 25](https://github.com/locationtech/proj4j/assets/32631467/c388a37c-2e95-464f-9570-331a92ccbcf6)

**Comment by pomadchin** [comment]
@Tom3652 if that's possible to generate a reproducible example that could be some bug that just got revealed by resources in different packages :+1:

**Comment by Tom3652** [comment]
@pomadchin i can't reproduce it for now but i know a real factor that causes the issue : 

When i set the Kotlin version of my app to `ext.kotlin_version = '1.8.0'` and my `gradle` to : 
`classpath 'com.android.tools.build:gradle:7.4.2'`
It works fine.

When i set them to the latest version : `ext.kotlin_version = '1.9.23'` and my `gradle` to : 
`classpath 'com.android.tools.build:gradle:8.3.2'`

Using Gradle 8.4 distribution instead of 7.5.1, it simply doesn't work. 

So the conclusion is that the newest version of Gradle / Kotlin compiling files is changing maybe the way `HashMap` behaves or how the Java is run,  i have no idea unfortunately i am a Flutter developer 😅

I will try to make reproductible example when i have the time, but for now my project is saved by rolling back to older version of Kotlin and Gradle ! 🙏🏼

**Comment by pomadchin** [comment]
That's interesting, I'd be curious to see diff in the bytecode ha.

**Comment by dprks** [comment]
Hi friends! I suspect that the issue is to do with the addition of [R8](https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#r8-full-mode), replacing Proguard for code optimisation. R8 appears to be more aggressive than Proguard, and perhaps it is for this reason that your projection classes are missing at runtime. 

I'm far from an expert on the matter, but hopefully you'll have similarly good luck by adding the following incantation to your `proguard-rules.pro` file: 
`-keep class org.locationtech.proj4j.proj.** { *; }`

This should keep all projection classes. If know at compile time which projections you'll need and you want to save a few bytes, you can probably instead choose to only keep the projections you'll need. e.g. 
`-keep class org.locationtech.proj4j.proj.LongLatProjection { *; }`

I hope this helps!

**Comment by Tom3652** [comment]
I confirm that this is definitely working now :)

**Comment by EMaksymenko** [comment]
I recommend to use more strict rule:
-keepclassmembers class * implements org.locationtech.proj4j.proj.Projection {
    public <init>(...);
}

Could you put it inside the library?

**Comment by pomadchin** [comment]
@EMaksymenko yea, don't see any reasons why not to; any PRs are welcome; however the proguard compat is not really the library concern.
