### ISSUE TITLE
Problem with omerc projection e.g. EPSG: 3375

### ISSUE THREAD

**Issue by osedok** [locationtech/proj4j#21]
Hi there guys, I am thinking about swapping my app (MapitGIS) to locationtech library, one of my users would like to use projection 3375, however I am running into similar problem as described here:

https://gis.stackexchange.com/questions/261723/proj4js-gives-wrong-result-for-epsg3375

for:  3.06268465621428, 101.70979078430528 (lat,lon) 

I am getting 744626.6428051005, -103618.62269607143 result.

Expected: 412597.532715, 338944.957259

Any idea?

Kind Regards,
Andrzej

**Comment by sunshine0576** [comment]
EPSG：3375     PROJECTION：Hotine_Oblique_Mercator

peoj4j   init Oblique_Mercator ？？？？Maybe that's the problem.

**Comment by sunshine0576** [comment]
http://epsg.io/transform#s_srs=4326&t_srs=3375&x=101.7097908&y=3.0626847
Result: 412597.532715, 338944.957259
