### ISSUE TITLE
Updating EPSG database

### ISSUE THREAD

**Issue by willcohen** [locationtech/proj4j#4]
What should the process be for updating the EPSG database? proj.4 uses version 9.2 [here](https://github.com/OSGeo/proj.4/commit/9ede4c65a92781ab4c1be5b0adac81ba593bfa8c) but I'm not sure how that file should be cited in terms of ownership on this project (especially re the Eclipse CLA).

Moreover, using an updated EPSG database causes the test from #3 to fail again. Would it be acceptable to change the test reprojected value to the one generated by converting the point through PostGIS (which itself uses actual proj.4)?

**Comment by dr-jts** [comment]
Answer to the second question:  I think it's acceptable to update the value to whatever value is returned by the new EPSG database (whether from proj4J itself, or some other source).  Hopefully it is now correct!  (Would be interesting to know why it has changed...)

Also, if the new value is simply less precise, perhaps the test precision should be reduced.  (It's always a bit hard to figure out how values should be treated for the more obscure projections).

**Comment by dr-jts** [comment]
For #1 - @lossyrob any ideas

**Comment by willcohen** [comment]
It seems like the epsg and world files in the nad folder are the two things that could use an update, and they come directly from proj.4. If the proj.4 project is, overall, MIT licensed, would it work to just put a reference in LICENSE to proj.4 and that it's MIT? If that sounds good, I can add that and update those two files.

**Comment by lossyrob** [comment]
@willcohen yes, updating the database and changing any tests that had previous 'incorrect' values (according to the new DB params) makes a lot of sense. Thanks!

**Comment by willcohen** [comment]
Thanks, just submitted! Also -- for what's it worth, there did seem to be Eclipse IP validation hooks when I submitted PRs #2 and #3, though #7 didn't get one just now.

**Comment by lossyrob** [comment]
Closed by #7
