### ISSUE TITLE
Making CRS instances case classes

### ISSUE THREAD

**Issue by metasim** [locationtech/proj4j#48]
Make for a bit more natural serialization, easier debugging, etc.

_Originally posted by @metasim in https://github.com/locationtech/geotrellis/pull/3039_

**Comment by metasim** [comment]
Strawdog architecture:

how's this for a strawdog:

![image](https://user-images.githubusercontent.com/131013/63477484-4e824280-c453-11e9-9a2a-7f31139cce9b.png)

When `fromWKT` or `fromProj4String` or `getEpsgCode` you'd get an instance of one of the intermediate classes. Common singletons are implemented as `case object`s.

**Comment by pomadchin** [comment]
Hey @metasim is not it a GeoTrellis issue? Since it looks like you are talking here about GeoTrellis wrapper types.

**Comment by metasim** [comment]
🤦‍♂
