### ISSUE TITLE
Support for parameters like R

### ISSUE THREAD

**Issue by skinkie** [locationtech/proj4j#54]
I am trying to implement https://gis.stackexchange.com/questions/344809/proj4-definition-for-wgs84-coordinates-multiplied-by-1000000/344829#344829 sadly the answer contains something where proj4j reports "R parameter is not supported". Is there an implementation reason not to support this from the library?

**Comment by pomadchin** [comment]
Hi @skinkie, this library just not a complete port of a PROJ library.
I think originally it was planned to add all the PROJ functions support, but there were not enough of time spent on that.

As your first steps, you can try to add it as a registered parameter [here](https://github.com/locationtech/proj4j/blob/3cf5063ccde36fcaa4f5424003ba791afa540389/src/main/java/org/locationtech/proj4j/parser/Proj4Keyword.java#L89) and to trace down the problems that would be introduced by adding this parameter support. 

I guess some parsers / transform functions just dont support it. You're welcome to work on the and we'll try to help you on that path :+1:
