### ISSUE TITLE
Setting earth radius The calculation result is wrong

### ISSUE THREAD

**Issue by jidengke** [locationtech/proj4j#70]
String  lccParam="+proj=lcc +lat_1=20.0 +lat_2=50.0 +lat_0=38.00001 +lon_0=102.0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +R=6370000 +no_defs";  
The calculation result is wrong

**Comment by pomadchin** [comment]
Hello, thanks for reporting! Could you prepare the failing test case? I.e. the code that generates a wrong result + what should be the expected result.

**Comment by jidengke** [comment]
code
`    public static void main(String[] args) {
        ProjCoordinate bl=new ProjCoordinate();
        bl.y=-4.504755;
        bl.x=65.324837;
        String wgsParam="+proj=longlat +datum=WGS84 +no_defs";
        String  lccParam="+proj=lcc +lat_1=20.0 +lat_2=50.0 +lat_0=38.00001 +lon_0=102.0 +x_0=0 +y_0=0 +ellps=CLEAR +units=m +no_defs";
        CoordinateTransformFactory ctFactory = new CoordinateTransformFactory();
        CRSFactory csFactory = new CRSFactory();
        CoordinateReferenceSystem source = csFactory.createFromParameters("wgs", wgsParam);
        CoordinateReferenceSystem target = csFactory.createFromParameters("lcc", lccParam);
        CoordinateTransform coordinateTransform = ctFactory.createTransform(source, target);
        ProjCoordinate t = new ProjCoordinate();
        coordinateTransform.transform(bl, t);
        System.out.println(t.x);
        System.out.println(t.y);
    }`

Program output
x=-4813708.6575989155
y=-3981769.0948999394

this is qgis output
x=-4009501.2945
y=-4819499.5840
![1615096378(1)](https://user-images.githubusercontent.com/25683591/110230520-7f9a6900-7f4c-11eb-9f20-ffad969ab14e.png)

**Comment by jidengke** [comment]
I tried to add a new datum to the source code
![1615097481(1)](https://user-images.githubusercontent.com/25683591/110230884-051f1880-7f4f-11eb-81d1-27819497193a.jpg)

`        String  lccParam="+proj=lcc +lat_1=20.0 +lat_2=50.0 +lat_0=38.00001 +lon_0=102.0 +x_0=0 +y_0=0 +ellps=CLEAR +units=m +no_defs";`

this output

x=-4819499.583995361
y=-4009501.2944552563
