### ISSUE TITLE
Backport all the dwins/proj4j PRs / improvements

### ISSUE THREAD

**Issue by pomadchin** [locationtech/proj4j#81]
It looks like there is a set of outstanding PRs agains https://github.com/dwins/proj4j which were never merged / ported into this codebase. This task is to track backports progress.

**Comment by sebasbaumh** [comment]
Just as a note: The open pull request https://github.com/dwins/proj4j/pull/5 was created by me and is already merged here using PR https://github.com/locationtech/proj4j/pull/29 .

**Comment by pomadchin** [comment]
@sebasbaumh yes, thank you! 

A list of PRs that makes sense to backport by @JesseCrocker:

* https://github.com/dwins/proj4j/pull/2
* https://github.com/dwins/proj4j/pull/3
