### ISSUE TITLE
UnknownAuthorityCodeException: EPSG:9054

### ISSUE THREAD

**Issue by imperio-wxm** [locationtech/proj4j#88]
```scala
val crs = new CRSFactory().createFromName("EPSG:9054")
println(crs)
```

```scala
EPSG:9054
org.locationtech.proj4j.UnknownAuthorityCodeException: EPSG:9054
	at org.locationtech.proj4j.CRSFactory.createFromName(CRSFactory.java:85)
```

9054 related configuration could not be found in https://github.com/locationtech/proj4j/blob/master/src/main/resources/proj4/nad/epsg

**Comment by pomadchin** [comment]
Hey @imperio-wxm, that's right! It's not here!

**Comment by imperio-wxm** [comment]
@pomadchin 
I got the PROJ.4 information from epsg.io, is it correct to add the following information to the file?
![image](https://user-images.githubusercontent.com/8111349/202841949-8ed3cb33-d180-4f34-9064-010362844451.png)
```shell
<9054> +proj=longlat +ellps=WGS84 +no_defs +type=crs  <>
```

**Comment by pomadchin** [comment]
Yes, I think it can be shrinked even to `+proj=longlat +datum=WGS84 +no_defs`
The only issue with it is that the proj4 string of this projection is a `EPSG:4326` alias.
